### PR TITLE
Particle display block

### PR DESCRIPTION
**Pull request by CallMeEchoCodes**
Pretty much just a particle system. Fairly simple.

UI is a little weird but I think it's alright for a first iteration, feedback is appreciated on that.

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
image
particle_display_block

early particle display texture opinion (drop the word block! it's the new trend)

**Comment by CallMeEchoCodes** [comment]
thats so much better. the texture i made was a very quick placeholder. thanks!

**Comment by CallMeEchoCodes** [comment]
texture done and block renamed :3

**Review by sleepingdragoninn — APPROVED** [review]
looks good to me! nice clean little solutions for the more complex UI bits

**Pull request merged**
