### PR TITLE
Adds hopper extraction for the item display block

### PR DESCRIPTION
**Pull request by Chailotl**

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
awesome!! out of curiosity, what is canPlayerUse used for?

**Comment by Chailotl** [comment]
It's a required method of the `Inventory` interface

**Comment by sleepingdragoninn** [comment]
ah so it's not actually functional here?

**Review by sleepingdragoninn — APPROVED** [review]
looks good!

**Comment by Chailotl** [comment]
> ah so it's not actually functional here?

Pretty much no, I think it's used by code that handles locking containers, and thus should always be false for the item display block

**Pull request merged**
