### PR TITLE
Add placeholder renders for blocks, change some textures

### LINKED ISSUE #41: Display item model of invisible blocks when holding a glowcase block
Good way to prevent losing text blocks in the air, or empty item blocks

### PR DESCRIPTION
**Pull request by sleepingdragoninn**
Closes #41

Adds placeholders that render whenever a block is empty, or the player is holding a glowcase item and isn't targeting the block.

Also changes the texture and render style of hyperlink and popup blocks to match - they're now larger, permanently fullbright, white with a shadow, and 16x16 instead of 32x32. Plus i swapped the sprite block to be a star texture.

image

https://github.com/user-attachments/assets/d1217695-b268-4d0a-a0b0-0090ff5c2076

Finally, I've reordered the creative tab as displays, player interactions, items.

image

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
Ready for review again!

image

image

interactable blocks are now half size, hyperlink and sprite have new textures, stuff is no longer backwards, and titles render.

also, if for some reason the player hovers over a placeholder and it _doesn't_ dissappear (e.g. it's a hyperlink block, or it's "empty" e.g. a text block with no text) the placeholder will tint. this makes text readable and makes it feel a lil more dynamic.

**Review by Chailotl — APPROVED** [review]
This looks good! I like the clean up and reorganization you did

Although non-blocking, I think the placeholder renders should be billboarded

**Comment by sleepingdragoninn** [comment]
thanks! I reckon disagree on the bilboarding though - I think we can billboard anything that doesn't have a rotation block property, but the ones that do should be as-is so you can see which way around the block is facing even without content / fixed settings enabled.

**Comment by sleepingdragoninn** [comment]
Blocks without rotation now bilboard to indicate they have no rotation. back faces of blocks with rotation are now darkened (easier to see than noticing the texture is backwards)

image

**Pull request merged**
